### ISSUE TITLE
verbose stack Error

### ISSUE THREAD

**Issue by greyfox7111** [efidiles/folder-template#9]
hello, I have followed the folder-template Getting started guide but I am receiving errors while running the generate command. I am new to github and npm and was wondering what the cause of the error could be. I noticed an open issue for windows environments; I am on a windows machine and was wondering if that might be the cause.

```
$ npm run generate component ./

> wp-dev@1.0.0 generate D:\_root\_Projects\_WWW\experimental\wp-content\themes\palpa
> ft "component" "./"

Current working directory:
~/D:\_root\_Projects\_WWW\experimental\wp-content\themes\palpa
task "component" is not registered
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-dev@1.0.0 generate: `ft "component" "./"`
npm ERR! Exit status 1
```
**npm log:**
[2018-01-21T22_37_01_445Z-debug.log](https://github.com/efidiles/folder-template/files/1650314/2018-01-21T22_37_01_445Z-debug.log)

*excerpt:*
```
9 verbose lifecycle wp-dev@1.0.0~generate: CWD: D:\_root\_Projects\_WWW\experimental\wp-content\themes\palpa
10 silly lifecycle wp-dev@1.0.0~generate: Args: [ '/d /s /c', 'ft "component" "./"' ]
11 silly lifecycle wp-dev@1.0.0~generate: Returned: code: 1  signal: null
12 info lifecycle wp-dev@1.0.0~generate: Failed to exec generate script
13 verbose stack Error: wp-dev@1.0.0 generate: `ft "component" "./"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\laragon\bin\nodejs\node-v8\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\laragon\bin\nodejs\node-v8\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Thank you very much for your time and help

**Comment by efidiles** [comment]
@greyfox7111 
If you're using windows then that's the reason you're getting that. I'm not using this package anymore and didn't bother to make it windows compatible
I'll take a look at it over the weekend to fix the issue on windows. I know what it is

---

On a separate note I would recommend to use this package: https://www.npmjs.com/package/plop

It's much better than this package and it's well maintained and all..

**Comment by greyfox7111** [comment]
@efidiles 
I understand, it is an excellent addition to npm nonetheless, I look forward to any updates as they come along. I plan to move to an ubuntu environment since i have faced difficulties with other npm packages as well. Thank you for your recommendation of the plop package. Although it is a little bit more complex to learn, I have been testing it out and is indeed working as i had hoped. Thanking you again very much for your time and help.
-all the best!
